### ISSUE TITLE
Minecraft was crashed with 1.19.3 mod build

### ISSUE THREAD

**Issue by Kodeekk** [Trainguy9512/locomotion#92]
*Mixins error*
```
[03/01/2023 16:09:27 PM] [main/INFO] SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:**USERSDIR**/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[03/01/2023 16:09:27 PM] [main/INFO] Compatibility level set to JAVA_17
[03/01/2023 16:09:27 PM] [main/WARN] Error loading class: net/minecraft/world/level/block/entity/BlockEntity (java.lang.ClassNotFoundException: net/minecraft/world/level/block/entity/BlockEntity)
[03/01/2023 16:09:27 PM] [main/WARN] @Mixin target net.minecraft.world.level.block.entity.BlockEntity was not found modid.mixins.json:MixinBlockEntity from mod animation_overhaul
[03/01/2023 16:09:27 PM] [main/WARN] Error loading class: net/minecraft/client/renderer/entity/layers/CapeLayer (java.lang.ClassNotFoundException: net/minecraft/client/renderer/entity/layers/CapeLayer)
[03/01/2023 16:09:27 PM] [main/WARN] @Mixin target net.minecraft.client.renderer.entity.layers.CapeLayer was not found modid.mixins.json:MixinCapeLayer from mod animation_overhaul
[03/01/2023 16:09:27 PM] [main/WARN] Error loading class: net/minecraft/client/renderer/entity/layers/ElytraLayer (java.lang.ClassNotFoundException: net/minecraft/client/renderer/entity/layers/ElytraLayer)
[03/01/2023 16:09:27 PM] [main/WARN] @Mixin target net.minecraft.client.renderer.entity.layers.ElytraLayer was not found modid.mixins.json:MixinElytraLayer from mod animation_overhaul
[03/01/2023 16:09:27 PM] [main/WARN] Error loading class: net/minecraft/client/renderer/GameRenderer (java.lang.ClassNotFoundException: net/minecraft/client/renderer/GameRenderer)
[03/01/2023 16:09:27 PM] [main/WARN] @Mixin target net.minecraft.client.renderer.GameRenderer was not found modid.mixins.json:MixinGameRenderer from mod animation_overhaul
[03/01/2023 16:09:27 PM] [main/WARN] Error loading class: net/minecraft/client/gui/screens/inventory/InventoryScreen (java.lang.ClassNotFoundException: net/minecraft/client/gui/screens/inventory/InventoryScreen)
[03/01/2023 16:09:27 PM] [main/WARN] @Mixin target net.minecraft.client.gui.screens.inventory.InventoryScreen was not found modid.mixins.json:MixinInventoryScreen from mod animation_overhaul
[03/01/2023 16:09:27 PM] [main/WARN] Error loading class: net/minecraft/client/renderer/entity/layers/ItemInHandLayer (java.lang.ClassNotFoundException: net/minecraft/client/renderer/entity/layers/ItemInHandLayer)
[03/01/2023 16:09:27 PM] [main/WARN] @Mixin target net.minecraft.client.renderer.entity.layers.ItemInHandLayer was not found modid.mixins.json:MixinItemInHandLayer from mod animation_overhaul
[03/01/2023 16:09:27 PM] [main/WARN] Error loading class: net/minecraft/world/entity/LivingEntity (java.lang.ClassNotFoundException: net/minecraft/world/entity/LivingEntity)
[03/01/2023 16:09:27 PM] [main/WARN] @Mixin target net.minecraft.world.entity.LivingEntity was not found modid.mixins.json:MixinLivingEntity from mod animation_overhaul
[03/01/2023 16:09:27 PM] [main/WARN] Error loading class: net/minecraft/client/renderer/entity/LivingEntityRenderer (java.lang.ClassNotFoundException: net/minecraft/client/renderer/entity/LivingEntityRenderer)
[03/01/2023 16:09:28 PM] [main/WARN] @Mixin target net.minecraft.client.renderer.entity.LivingEntityRenderer was not found modid.mixins.json:MixinLivingEntityRenderer from mod animation_overhaul
[03/01/2023 16:09:28 PM] [main/WARN] Error loading class: net/minecraft/client/model/geom/ModelPart (java.lang.ClassNotFoundException: net/minecraft/client/model/geom/ModelPart)
[03/01/2023 16:09:28 PM] [main/WARN] @Mixin target net.minecraft.client.model.geom.ModelPart was not found modid.mixins.json:MixinModelPart from mod animation_overhaul
[03/01/2023 16:09:28 PM] [main/WARN] Error loading class: net/minecraft/client/gui/components/DebugScreenOverlay (java.lang.ClassNotFoundException: net/minecraft/client/gui/components/DebugScreenOverlay)
[03/01/2023 16:09:28 PM] [main/WARN] @Mixin target net.minecraft.client.gui.components.DebugScreenOverlay was not found modid.mixins.json:debug.MixinDebugScreenOverlay from mod animation_overhaul
[03/01/2023 16:09:28 PM] [main/WARN] Error loading class: net/minecraft/client/model/PlayerModel (java.lang.ClassNotFoundException: net/minecraft/client/model/PlayerModel)
[03/01/2023 16:09:28 PM] [main/WARN] @Mixin target net.minecraft.client.model.PlayerModel was not found modid.mixins.json:models.MixinPlayerModel from mod animation_overhaul 
```
*---- Minecraft Crash Report ----*
```
[03/01/2023 16:09:52 PM] // Who set us up the TNT?
[03/01/2023 16:09:52 PM] 
[03/01/2023 16:09:52 PM] Time: 2023-01-03 16:09:52
[03/01/2023 16:09:52 PM] Description: Initializing game
[03/01/2023 16:09:52 PM] 
[03/01/2023 16:09:52 PM] java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'animation_overhaul'!
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
[03/01/2023 16:09:52 PM] 	at net.minecraft.class_310.<init>(class_310.java:465)
[03/01/2023 16:09:52 PM] 	at net.minecraft.client.main.Main.method_44604(Main.java:205)
[03/01/2023 16:09:52 PM] 	at net.minecraft.client.main.Main.main(Main.java:51)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[03/01/2023 16:09:52 PM] Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/packs/PackType
[03/01/2023 16:09:52 PM] 	at com.trainguy9512.animationoverhaul.AnimationOverhaulMain.registerTimelineGroupLoader(AnimationOverhaulMain.java:47)
[03/01/2023 16:09:52 PM] 	at com.trainguy9512.animationoverhaul.AnimationOverhaulMain.onClientInit(AnimationOverhaulMain.java:28)
[03/01/2023 16:09:52 PM] 	at com.trainguy9512.animationoverhaul.AnimationOverhaulMain.onInitialize(AnimationOverhaulMain.java:53)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[03/01/2023 16:09:52 PM] 	... 8 more
[03/01/2023 16:09:52 PM] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.packs.PackType
[03/01/2023 16:09:52 PM] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[03/01/2023 16:09:52 PM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
[03/01/2023 16:09:52 PM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[03/01/2023 16:09:52 PM] 	... 12 more
[03/01/2023 16:09:52 PM] 
[03/01/2023 16:09:52 PM] 
[03/01/2023 16:09:52 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[03/01/2023 16:09:52 PM] ---------------------------------------------------------------------------------------
[03/01/2023 16:09:52 PM] 
[03/01/2023 16:09:52 PM] -- Head --
[03/01/2023 16:09:52 PM] Thread: Render thread
[03/01/2023 16:09:52 PM] Stacktrace:
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
[03/01/2023 16:09:52 PM] 	at net.minecraft.class_310.<init>(class_310.java:465)
[03/01/2023 16:09:52 PM] 
[03/01/2023 16:09:52 PM] -- Initialization --
[03/01/2023 16:09:52 PM] Details:
[03/01/2023 16:09:52 PM] 	Modules: 
[03/01/2023 16:09:52 PM] Stacktrace:
[03/01/2023 16:09:52 PM] 	at net.minecraft.client.main.Main.method_44604(Main.java:205)
[03/01/2023 16:09:52 PM] 	at net.minecraft.client.main.Main.main(Main.java:51)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[03/01/2023 16:09:52 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[03/01/2023 16:09:52 PM] 
[03/01/2023 16:09:52 PM] -- System Details --
[03/01/2023 16:09:52 PM] Details:
[03/01/2023 16:09:52 PM] 	Minecraft Version: 1.19.3
[03/01/2023 16:09:52 PM] 	Minecraft Version ID: 1.19.3
[03/01/2023 16:09:52 PM] 	Operating System: Linux (amd64) version 6.0.14-1-MANJARO
[03/01/2023 16:09:52 PM] 	Java Version: 17.0.3, Microsoft
[03/01/2023 16:09:52 PM] 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
[03/01/2023 16:09:52 PM] 	Memory: 1930063208 bytes (1840 MiB) / 2281701376 bytes (2176 MiB) up to 4294967296 bytes (4096 MiB)
[03/01/2023 16:09:52 PM] 	CPUs: 4
[03/01/2023 16:09:52 PM] 	Processor Vendor: GenuineIntel
[03/01/2023 16:09:52 PM] 	Processor Name: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
[03/01/2023 16:09:52 PM] 	Identifier: Intel64 Family 6 Model 61 Stepping 4
[03/01/2023 16:09:52 PM] 	Microarchitecture: Broadwell (Client)
[03/01/2023 16:09:52 PM] 	Frequency (GHz): 2.20
[03/01/2023 16:09:52 PM] 	Number of physical packages: 1
[03/01/2023 16:09:52 PM] 	Number of physical CPUs: 2
[03/01/2023 16:09:52 PM] 	Number of logical CPUs: 4
[03/01/2023 16:09:52 PM] 	Graphics card #0 name: HD Graphics 5500
[03/01/2023 16:09:52 PM] 	Graphics card #0 vendor: Intel Corporation (0x8086)
[03/01/2023 16:09:52 PM] 	Graphics card #0 VRAM (MB): 256.00
[03/01/2023 16:09:52 PM] 	Graphics card #0 deviceId: 0x1616
[03/01/2023 16:09:52 PM] 	Graphics card #0 versionInfo: unknown
[03/01/2023 16:09:52 PM] 	Virtual memory max (MB): 12940.40
[03/01/2023 16:09:52 PM] 	Virtual memory used (MB): 6858.77
[03/01/2023 16:09:52 PM] 	Swap memory total (MB): 9011.20
[03/01/2023 16:09:52 PM] 	Swap memory used (MB): 1186.92
[03/01/2023 16:09:52 PM] 	JVM Flags: 11 total; -XX:-OmitStackTraceInFastThrow -Xms1024M -Xmx4096M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xss1M
[03/01/2023 16:09:52 PM] 	Fabric Mods: 
[03/01/2023 16:09:52 PM] 		animation_overhaul: Trainguy's Animation Overhaul 1.0.0
[03/01/2023 16:09:52 PM] 		fabric-api: Fabric API 0.68.1+1.19.3
[03/01/2023 16:09:52 PM] 			fabric-api-base: Fabric API Base 0.4.19+8d1895cf72
[03/01/2023 16:09:52 PM] 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.18+49abcf7e72
[03/01/2023 16:09:52 PM] 			fabric-biome-api-v1: Fabric Biome API (v1) 12.0.0+689f5e7172
[03/01/2023 16:09:52 PM] 			fabric-block-api-v1: Fabric Block API (v1) 1.0.3+12bfe4ea72
[03/01/2023 16:09:52 PM] 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.28+c6af733c72
[03/01/2023 16:09:52 PM] 			fabric-client-tags-api-v1: Fabric Client Tags 1.0.9+49abcf7e72
[03/01/2023 16:09:52 PM] 			fabric-command-api-v1: Fabric Command API (v1) 1.2.19+f71b366f72
[03/01/2023 16:09:52 PM] 			fabric-command-api-v2: Fabric Command API (v2) 2.1.15+49abcf7e72
[03/01/2023 16:09:52 PM] 			fabric-commands-v0: Fabric Commands (v0) 0.2.36+df3654b372
[03/01/2023 16:09:52 PM] 			fabric-containers-v0: Fabric Containers (v0) 0.1.44+df3654b372
[03/01/2023 16:09:52 PM] 			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.11+49abcf7e72
[03/01/2023 16:09:52 PM] 			fabric-convention-tags-v1: Fabric Convention Tags 1.1.9+2894d6df72
[03/01/2023 16:09:52 PM] 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.12+aeb40ebe72
[03/01/2023 16:09:52 PM] 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.0.1+65e415cb72
[03/01/2023 16:09:52 PM] 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.39+48349a3f72
[03/01/2023 16:09:52 PM] 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.5+b83334a072
[03/01/2023 16:09:52 PM] 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.37+422b77fb72
[03/01/2023 16:09:52 PM] 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.38+df3654b372
[03/01/2023 16:09:52 PM] 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.28+2894d6df72
[03/01/2023 16:09:52 PM] 			fabric-item-api-v1: Fabric Item API (v1) 2.1.4+fa25da9972
[03/01/2023 16:09:52 PM] 			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.6+b7096da872
[03/01/2023 16:09:52 PM] 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.28+aaaf9d3372
[03/01/2023 16:09:52 PM] 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.26+df3654b372
[03/01/2023 16:09:52 PM] 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.8+2894d6df72
[03/01/2023 16:09:52 PM] 			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.17+75e9821172
[03/01/2023 16:09:52 PM] 			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.21+9e7660c672
[03/01/2023 16:09:52 PM] 			fabric-message-api-v1: Fabric Message API (v1) 5.0.12+6ede1da972
[03/01/2023 16:09:52 PM] 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.28+49abcf7e72
[03/01/2023 16:09:52 PM] 			fabric-models-v0: Fabric Models (v0) 0.3.25+11ba9c3b72
[03/01/2023 16:09:52 PM] 			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.14+d9ac3c3972
[03/01/2023 16:09:52 PM] 			fabric-networking-v0: Fabric Networking (v0) 0.3.31+df3654b372
[03/01/2023 16:09:52 PM] 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.1.6+49abcf7e72
[03/01/2023 16:09:52 PM] 			fabric-particles-v1: Fabric Particles (v1) 1.0.18+fbde993d72
[03/01/2023 16:09:52 PM] 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.1+2608564672
[03/01/2023 16:09:52 PM] 			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.1.0+2063beff72
[03/01/2023 16:09:52 PM] 			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.23+11ba9c3b72
[03/01/2023 16:09:52 PM] 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.28+df3654b372
[03/01/2023 16:09:52 PM] 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.23+48349a3f72
[03/01/2023 16:09:52 PM] 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.16+3067f46372
[03/01/2023 16:09:52 PM] 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.31+df3654b372
[03/01/2023 16:09:52 PM] 			fabric-rendering-v1: Fabric Rendering (v1) 1.11.7+49abcf7e72
[03/01/2023 16:09:52 PM] 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.0+280be3ab72
[03/01/2023 16:09:52 PM] 	Launched Version: 1.19.3
[03/01/2023 16:09:52 PM] 	Backend library: LWJGL version 3.3.1 SNAPSHOT
[03/01/2023 16:09:52 PM] 	Backend API: Unknown
[03/01/2023 16:09:52 PM] 	Window size: <not initialized>
[03/01/2023 16:09:52 PM] 	GL Caps: Using framebuffer using OpenGL 3.2
[03/01/2023 16:09:52 PM] 	GL debug messages: <disabled>
[03/01/2023 16:09:52 PM] 	Using VBOs: Yes
[03/01/2023 16:09:52 PM] 	Is Modded: Definitely; Client brand changed to 'fabric'
[03/01/2023 16:09:52 PM] 	Type: Client (map_client.txt)
[03/01/2023 16:09:52 PM] 	CPU: <unknown>
[03/01/2023 16:09:52 PM] #@!@# Game crashed! Crash report saved to: #@!@# **USERSDIR**/instances/Minecraft1193withFabric/crash-reports/crash-2023-01-03_16.09.52-client.txt
[03/01/2023 16:09:52 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
```
Im using [ATLauncher](https://atlauncher.com/)
There are two mods I was using when these errors appeared: 
![image](https://user-images.githubusercontent.com/104493048/210388896-41da44aa-5ef5-4660-9cf5-00d6a35e8efc.png)
I love this mod too much, I'm not ready to give up playing with it :(

**Comment by RMF-AndyPlayz** [comment]
Can confirm. Minecraft exits with code -1

**Comment by AgentYgh** [comment]
I seem to be having the same error as well

**Comment by OmegaXVVII** [comment]
How did you even get it to work with 1.19.3?

**Comment by JeffBezos2** [comment]
Yeah how
